feat(elasticache-redis): add engine input for valkey support
cloudposse/terraform-aws-components pull request #1170
Opened 2024-10-29 01:01 UTC by nitrocode

## what

- add engine input for valkey support

## why

- Valkey is far cheaper than redis

## references

- https://github.com/cloudposse/terraform-aws-elasticache-redis/releases/tag/v1.7.0

2024-10-29 13:47 UTC, GabisCampana commented
@Nuru

2024-10-29 17:57 UTC, Nuru requested changes
Please enumerate the legal values of `engine` in the variable description. Please also provide, in the README, an explanation of what they mean, with one or more links to even more information.

2024-10-29 17:57 UTC, Nuru commented on modules/elasticache-redis/modules/redis_cluster/variables.tf
> +  description = "Name of the cache engine"
```suggestion
  description = "Name of the cache engine to use: either `redis` or `valkey`"
```

2024-10-29 17:57 UTC, Nuru commented on modules/elasticache-redis/modules/redis_cluster/variables.tf
>    description = "Redis Version"
```suggestion
  description = "Version of the cache engine to use"
```

2024-10-30 20:27 UTC, nitrocode commented
@Nuru changes addressed, please re-review.

2024-10-30 21:05 UTC, Nuru approved these changes

2024-10-30 21:06 UTC, merged