feat(elasticache): add snapshot retention limit
cloudposse/terraform-aws-components pull request #1171
Opened 2024-10-30 20:34 UTC by nitrocode

## what

- feat(elasticache): add snapshot retention limit

## why

- Resolves [ElastiCache.1](https://docs.aws.amazon.com/securityhub/latest/userguide/elasticache-controls.html#elasticache-1) (ElastiCache (Redis OSS) clusters should have automatic backups enabled) securityhub control by giving the ability to set this value to a number greater than 0

## references

- Default is 0 https://github.com/cloudposse/terraform-aws-elasticache-redis/blob/9104d9a6a120ae9c90f59c5eb4ea711cc2d2c6bb/variables.tf#L223-L227
- Module received the feature 5 years ago so no need to update the module version https://github.com/cloudposse/terraform-aws-elasticache-redis/pull/45
- Related PR #1170 which upgrades the module

2024-10-31 17:47 UTC, GabisCampana commented
@Nuru

2024-11-01 22:20 UTC, Nuru requested changes

2024-11-01 22:20 UTC, Nuru commented on modules/elasticache-redis/modules/redis_cluster/variables.tf
> +    snapshot_retention_limit        = bool
```suggestion
    snapshot_retention_limit        = number
```

2024-11-02 00:33 UTC, nitrocode commented on modules/elasticache-redis/modules/redis_cluster/variables.tf
> +    snapshot_retention_limit        = bool
Good catch! Thank you

2024-11-04 18:05 UTC, Nuru approved these changes

2024-11-04 18:06 UTC, merged