feat: updates EKS component to latest
cloudposse/terraform-aws-components pull request #300
Opened 2021-04-05 19:33 UTC by Gowiem

## what
* Updates the EKS component to the latest from downstream
* Updates pre-commit-terraform version to utilize latest terraform-docs version / README updates

## why
* We're going to be utilizing the EKS component in our upcoming tutorial so we wanted to be sure to be using the latest
* Bunch of terraform-docs updates recently, so utilizing the latest ensures we're keeping up-to-date with the improved README format.

2021-04-05 19:41 UTC, Gowiem commented on modules/eks/default.auto.tfvars
> +cluster_kubernetes_version = "1.18"
Note, bumping to version `1.18` since figured that is preferable. We can also update to `1.19` as well since that is out.

2021-04-05 19:41 UTC, Gowiem commented on modules/eks/main.tf
> +  primary_role_map   = module.primary_roles.outputs.role_name_role_arn_map
@osterman Will have to see how this component dependency shakes out in regards to our single AWS Account tutorial idea.

2021-04-05 19:41 UTC, Gowiem commented on modules/eks/providers.tf
> +provider "aws" {
@osterman you and I talked about this lightly but we didn't come up with an action item I don't believe... it seems funky that we're requiring spotinst for our EKS component. Do we potentially want to pull this out to its own component like `eks-with-spotinst` or a fully separate `spotinst-eks-node-group` component? cc @aknysh

2021-11-02 22:43 UTC, Nuru requested changes
This is not close to the current eks component. Please upgrade to current 
- context.tf 0.25.0
- eks-cluster 0.43.2
- eks-node-group 0.26.2

2021-11-03 01:14 UTC, Gowiem commented
This is ancient as we never got around to getting it review and it looks like @nitrocode is working on the continuation of this work in #373. I'll let him take it from here 👍

2021-11-03 01:14 UTC, closed without merging