Fixes and changes to spin up a brand new atmos stack
cloudposse/terraform-aws-components pull request #329
Opened 2021-06-01 13:53 UTC by iliazlobin

## what
* changes to remote-state code pattern to address previously identified issues:
  * https://github.com/cloudposse/terraform-aws-components/issues/324
  * https://github.com/cloudposse/terraform-aws-components/issues/323
* fixed an embedded module modules/account-map/modules/iam-roles to use the remote-state module instead of a data source
* updated remote-state module versions in all places
* modified providers for the bootstrapping components in order to spin up stacks using master/root roles
* removed spot instances support in eks (to deploy without it unconditionally)
* removed a buggy system-manager file support in eks (to deploy without it unconditionally)

## why
* Just to show the minimum amount of fixes to the upstream source code in order to successfully deploy a prime atmos stack

2021-06-01 18:01 UTC, Nuru requested changes

2021-06-01 18:01 UTC, Nuru commented on modules/sso/providers.tf
> +    role_arn = var.aws_assume_role_arn
All the changes to this file should be reverted

2021-06-01 18:01 UTC, Nuru commented on modules/vpc-flow-logs-bucket/providers.tf
> +    role_arn = var.aws_assume_role_arn
All the changes to this file should be reverted

2021-06-01 18:01 UTC, Nuru commented on modules/vpc/providers.tf
> +  source = "../account-map/modules/iam-roles"
Revert

2021-06-01 18:21 UTC, Nuru commented
I rejected the changes to the providers for the bootstrap components because they create or modify IAM roles and/or authentication so you cannot use the roles they create to create them (which is why they are called "bootstrap" components).

2021-06-02 08:47 UTC, iliazlobin commented on modules/eks/versions.tf
> +      version = "~> 2.2.0"
We were able to deploy the eks component with version 2.2.0 quite successfuly. Could it be that the problem was related to some of the previous versions of the k8s provider (2.1.x) that's been fixed in 2.2.0?

2021-06-04 08:20 UTC, sgtoj commented
Maybe I am mistaken, but I don think you meant to commit...
```
modules/tfstate-backend/gbl-root-tfstate-backend.planfile
```

2021-07-29 18:07 UTC, nitrocode commented
I think this was included on accident as well `gbl-root-tfstate-backend.tfplan`.

2021-07-29 18:09 UTC, nitrocode commented on modules/efs/main.tf
> +  source = "git::https://github.com/cloudposse/terraform-aws-efs.git?ref=tags/0.30.1"
nit: We should use the more popular `source`

```suggestion
  source  = "cloudposse/efs/aws"
  version = "0.30.1"
```

2021-08-09 14:17 UTC, nitrocode commented on modules/efs/remote-state.tf
> +  count = var.use_eks_security_group ? 1 : 0
```suggestion
  count   = var.use_eks_security_group ? 1 : 0
```

2022-08-25 22:17 UTC, closed without merging

2022-08-25 22:20 UTC, Benbentwo commented
Closed this as it has become stale, most of the components referenced by this branch and PR have been superseded or updated.