feat(github-action-plan-storage): added
cloudposse/terraform-aws-components pull request #596
Opened 2023-03-16 02:23 UTC by dudymas

## what
* terraform plan storage for github actions

## why
* supports [github-action-terraform-plan-storage](https://github.com/cloudposse/github-action-terraform-plan-storage)

## references
* https://cloudposse.atlassian.net/browse/VANGUARD-107

2023-03-16 15:15 UTC, mcalhoun requested changes
Looks like a great start, thanks! I left a few comments.

2023-03-16 15:15 UTC, mcalhoun commented on modules/github-action-plan-storage/iam.tf
> +      "${module.tfstate_backend.tfstate_backend_s3_bucket_arn}/*",
I think this also needs `${module.tfstate_backend.tfstate_backend_s3_bucket_arn}` (without the splat) in order for the ListBucket to work properly.

2023-03-16 16:36 UTC, dudymas commented on modules/github-action-plan-storage/iam.tf
> +      "dynamodb:DeleteItem"
gotcha. fixing

2023-03-16 17:05 UTC, dudymas commented on modules/github-action-plan-storage/main.tf
adding that neow

2023-03-21 15:41 UTC, osterman commented on modules/github-action-plan-storage/main.tf
> +}
It's considered bad practice to source root modules as child modules. Root modules have a state backend.

2023-10-27 23:29 UTC, dudymas commented
Closing as stale

2023-10-27 23:29 UTC, closed without merging