fix: distinct names for lambda monitors in datadog-monitor
cloudposse/terraform-aws-components pull request #689
Opened 2023-05-22 18:11 UTC by dudymas

## what
* better qualify the name of lambda monitors

## why
* names were colliding and preventing multiple lambda monitors for different
stages
* name had invalid template text

2023-05-22 18:14 UTC, Benbentwo approved these changes

2023-05-22 21:53 UTC, batkins-carecloud requested changes

2023-05-22 21:53 UTC, batkins-carecloud commented on modules/datadog-monitor/catalog/monitors/lambda.yaml
> +  name: AWS Lambda ${ tenant }-${ environment }-${ stage } has errors
The lambda-log-forwarder monitor needs the same fully qualified name. name: "(Lambda) ${ tenant }-${ environment }-${ stage } - Datadog Lambda Forwarder Config Changed"

https://github.com/cloudposse/terraform-aws-components/blob/f7a75efa0585257556f1ce36bd547afed4fb714a/modules/datadog-monitor/catalog/monitors/lambda-log-forwarder.yaml#L5

2023-10-27 21:55 UTC, max-lobur commented
this was fixed in #887

2023-10-27 21:55 UTC, closed without merging