Added log-delivery-policy for s3-bucket component
cloudposse/terraform-aws-components pull request #698
Opened 2023-05-25 10:51 UTC by zdmytriv

## what
* Added log-delivery-policy for s3-bucket component

## why
* Added log-delivery-policy for s3-bucket component

## references

2023-05-25 18:51 UTC, Nuru requested changes

2023-05-25 19:04 UTC, zdmytriv commented on modules/s3-bucket/main.tf
>      bucket_name = var.logging_bucket_name_rendering_enabled ? format(var.logging_bucket_name_rendering_template, var.namespace, var.tenant, var.environment, var.stage, var.logging.bucket_name) : var.
fixed

2023-05-25 19:17 UTC, zdmytriv commented on modules/s3-bucket/variables.tf
> +  Whether to enable or disable the log delivery policy. Conflicts with `var.custom_policy_enabled` and `var.iam_policy_statements`".
Oops you are right, fixed

2023-05-25 19:22 UTC, zdmytriv commented on modules/s3-bucket/variables.tf
> +  It will be used if `var.custom_policy_enabled` and `var.log_delivery_policy_enabled` are set to `false`.
nope.

When `custom_policy_enabled=true` policy from `iam.tf` [this](https://github.com/cloudposse/terraform-aws-components/pull/698/files#diff-37adfa2463603828781680ac4b93d07be0be369e8aed2a393f56784733b3cd08R1-R18) will be used.

When `iam_policy_statements=true` (and other 2 are `false`) policy from `iam-policy` module will be used [this](https://github.com/cloudposse/terraform-aws-components/pull/698/files#diff-0f985f94d08f26bd28e34176ac4fd45f37a344c744703939cc33217a6a843a96R25-R42)

2023-05-25 20:25 UTC, zdmytriv commented on modules/s3-bucket/iam.tf
> +      format("arn:%s:s3:::%s", local.aws_partition, module.this.id),
I was also wondering why it is done this way but didn't want to change extra not related to this PR stuff.

Fixed

2023-05-25 20:26 UTC, zdmytriv commented
@Nuru please re-review

2024-10-03 18:13 UTC, Nuru requested changes
@zdmytriv I appreciate the motivation behind this PR and the effort you put into it. I am, however, not inclined to accept this PR for a few reasons. (Although I'm using the "Request changes" feature, I'm not asking you to make changes to make the PR acceptable, I'm asking you to close the PR without merging.)

To begin with, the log delivery policy you have added is not the [current "best practice" policy](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-s3-permissions.html). The current best practice is to include conditionals on the source account and ARN to guard against the confused deputies problem. (See the link for more details.)

Next, the name "custom policy" of the input to the current component is a bit misleading. Both the custom policy and the default policy are user supplied policies, just with different formats. This component does not provide any pre-defined policies. Adding a pre-defined policy makes this component even more complicated, and invites future users to want to be able to combine custom and pre-defined policies in a way that will cause further confusion and headache.

Cloud Posse already provides other components and modules for log delivery buckets, such as `vpc-flow-logs-bucket` and `cloudtrail-bucket` to handle the cases where the S3 bucket is for log delivery. These are much easier to use because they are pre-tuned for specific purposes. This component (s3-bucket) is meant for maximum flexibility, and users can and should create their own policies for it.

So I suggest you use one of the other components that meets your needs and please close this PR.

2024-10-03 18:18 UTC, closed without merging