feat: use `account-map` component for brownfield env
cloudposse/terraform-aws-components pull request #945
Opened 2024-01-06 04:45 UTC by nitrocode

## what

- feat: use `account-map` component for brownfield env

## why

- Allow brownfield environments to use the account-map component with existing accounts

## references

- Related to PR #943

2024-01-23 01:19 UTC, Nuru requested changes

2024-01-23 01:19 UTC, Nuru commented on modules/account-map/main.tf
> +  full_account_map = { for k, v in module.accounts.outputs.account_info_map : k => v.id if contains(local.non_suspended_account_ids, v.id) }
What is the advantage of this change?

Note that this is unacceptable in any case because it removes the renaming of the root account.

2024-10-03 14:41 UTC, closed without merging

2024-10-03 14:41 UTC, goruha commented
Close this PR as it does not add any additional value

2024-10-03 19:30 UTC, nitrocode commented
Ouch